import './globals.css'
import Head from 'next/head'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/NavBar'
import Footer from '@/components/Footer'

const montserrat = Montserrat({
  weight:["300", "300"],
  subsets:["latin"],
  variable:"--font-montserrat"
})

export const metadata = {
  title: 'Fancy Artsy App',
  description: 'Generated by fancy artsy app',
  keyWords: 'epoxy resin'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`${montserrat.variable} flex flex-col min-h-screen bg-white`}>
        <main>
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}